#!/usr/bin/env bun

import { writeFileSync } from "node:fs";
import packageJson from "./package.json" with { type: "json" };


const code =
// eslint-disable-next-line @stylistic/indent
`// Auto-generated by generate-version.ts
// Do not edit manually

export const VERSION = "${packageJson.version}";
`;

writeFileSync("src/version.ts", code, "utf8");

console.info(`✓ Generated version.ts with ${packageJson.version}`);
