export const initTemplate = {
	$schema: "https://fln.nesvet.dev/schema",
	output: "output.md",
	overwrite: false,
	exclude: [] as string[],
	// "exclude": [ "*.log", "!important.log" ],
	include: [] as string[],
	only: [] as string[],
	includeHidden: false,
	gitignore: true,
	maxFileSize: "10mb",
	maxTotalSize: "0",
	maxTokens: 0,
	maxContentTokens: 0,
	tokenModel: "estimate",
	strictLimits: false,
	compress: false,
	outline: false,
	encoding: "auto",
	format: "md",
	followSymlinks: false,
} as const;
