#!/usr/bin/env bun

import { writeFileSync } from "node:fs";
import { resolve } from "node:path";
import packageJson from "../package.json" with { type: "json" };


const root = resolve(import.meta.dir, "..");

const code =
// eslint-disable-next-line @stylistic/indent
`// Auto-generated by scripts/generate-version.ts
// Do not edit manually

export const VERSION = "${packageJson.version}";
`;

writeFileSync(resolve(root, "src/version.ts"), code, "utf8");

console.info(`✓ Generated version.ts with ${packageJson.version}`);
