#!/usr/bin/env bun

import { mkdirSync, writeFileSync } from "node:fs";
import { join, resolve } from "node:path";
import {
	CLI_FLAG_SPECS,
	CLI_SUBCOMMANDS,
	type CliFlagSpec,
	FLATTEN_FORMAT_VALUES,
	flagLongOption,
	flagShortOption,
	INIT_FLAG_NAMES,
	TEXT_JSON_FORMAT_VALUES,
} from "../src/cli/flagsManifest.js";

const completionsDir = resolve(import.meta.dir, "..", "completions");
const generatedBanner =
	"# Generated by scripts/generate-completions.ts — do not edit by hand.\n";

type FormatCompletionKind = "md-json" | "text-json";

function formatValues(kind: FormatCompletionKind): string {
	return kind === "md-json"
		? FLATTEN_FORMAT_VALUES.join(" ")
		: TEXT_JSON_FORMAT_VALUES.join(" ");
}

function initFlags(): CliFlagSpec[] {
	const names = new Set<string>(INIT_FLAG_NAMES);

	return CLI_FLAG_SPECS.filter((spec) => names.has(spec.name));
}

function flattenFlags(): CliFlagSpec[] {
	return CLI_FLAG_SPECS;
}

function bashLongOpts(specs: CliFlagSpec[]): string {
	return specs.map((spec) => flagLongOption(spec)).join(" ");
}

function bashShortOpts(specs: CliFlagSpec[]): string {
	return specs
		.flatMap((spec) => {
			const short = flagShortOption(spec);

			return short ? [short] : [];
		})
		.join(" ");
}

function generateBash(): string {
	const all = flattenFlags();
	const initOnly = initFlags();
	const subcommands = CLI_SUBCOMMANDS.join(" ");

	return `${generatedBanner}
# Bash completion for fln. Source this file or install to a bash-completion.d path.
#   source /path/to/completions/fln.bash

_fln() {
	local cur prev words cword
	_init_completion -s || return
	
	local subcmd=""
	if (( cword >= 2 )); then
		local first="\${words[1]}"
		for candidate in ${subcommands}; do
			if [[ "\${first}" == "\${candidate}" ]]; then
				subcmd="\${candidate}"
				break
			fi
		done
	fi
	
	case "\${subcmd}" in
	init)
		local init_opts="${bashLongOpts(initOnly)} ${bashShortOpts(initOnly)}"
		COMPREPLY=( $(compgen -W "\${init_opts}" -- "\${cur}") )
		return
		;;
	why)
		if [[ "\${cur}" == -* ]]; then
			local why_opts="${bashLongOpts(all)} ${bashShortOpts(all)}"
			COMPREPLY=( $(compgen -W "\${why_opts}" -- "\${cur}") )
			return
		fi
		if (( cword == 2 )); then
			compopt -o filenames
			COMPREPLY=( $(compgen -f -- "\${cur}") )
			return
		fi
		if (( cword == 3 )); then
			compopt -o filenames
			COMPREPLY=( $(compgen -d -- "\${cur}") )
			return
		fi
		return
		;;
	doctor)
		if [[ "\${cur}" == -* ]]; then
			local doctor_opts="${bashLongOpts(all)} ${bashShortOpts(all)}"
			COMPREPLY=( $(compgen -W "\${doctor_opts}" -- "\${cur}") )
			return
		fi
		if (( cword == 2 )); then
			compopt -o filenames
			COMPREPLY=( $(compgen -d -- "\${cur}") )
			return
		fi
		return
		;;
	esac
	
	if (( cword == 1 )); then
		if [[ "\${cur}" == -* ]]; then
			local global_opts="${bashLongOpts(all)} ${bashShortOpts(all)}"
			COMPREPLY=( $(compgen -W "\${global_opts}" -- "\${cur}") )
			return
		fi
		COMPREPLY=( $(compgen -W "${subcommands}" -- "\${cur}") )
		compopt -o filenames
		COMPREPLY+=( $(compgen -d -- "\${cur}") )
		return
	fi
	
	if [[ "\${cur}" == -* ]]; then
		local global_opts="${bashLongOpts(all)} ${bashShortOpts(all)}"
		COMPREPLY=( $(compgen -W "\${global_opts}" -- "\${cur}") )
		return
	fi
	
	compopt -o filenames
	COMPREPLY=( $(compgen -d -- "\${cur}") )
}

complete -F _fln fln
`;
}

function zshFlagArgument(
	spec: CliFlagSpec,
	formatKind: FormatCompletionKind,
): string {
	const long = flagLongOption(spec);
	const short = flagShortOption(spec);
	const prefix = short ? `{${short},${long}}` : long;
	if (spec.type === "boolean") return prefix;
	if (spec.name === "format")
		return `${prefix}:[format:${formatValues(formatKind)}]`;

	return `${prefix}:[value]`;
}

function zshSpecsBlock(
	specs: CliFlagSpec[],
	formatKind: FormatCompletionKind,
): string {
	return specs
		.map((spec) => `\t\t${zshFlagArgument(spec, formatKind)} \\`)
		.join("\n");
}

function generateZsh(): string {
	const all = flattenFlags();
	const initOnly = initFlags();

	return `${generatedBanner}#compdef fln

# Zsh completion for fln. Add completions/ to fpath, then:
#   autoload -Uz compinit && compinit

_fln() {
	local context state line
	typeset -A opt_args
	
	if (( CURRENT == 2 )) && [[ "\${words[2]}" != -* ]]; then
		_arguments -C \\
			"1: :(${CLI_SUBCOMMANDS.join(" ")})" \\
			"*::directory:_files -/" \\
${zshSpecsBlock(all, "md-json")}
		return
	fi
	
	case "\${words[2]}" in
	init)
		_fln_init
		;;
	why)
		_fln_why
		;;
	doctor)
		_fln_doctor
		;;
	plan)
		_arguments -C \\
			':directory:_files -/' \\
${zshSpecsBlock(all, "md-json")}
		;;
	diff)
		_arguments -C \\
			':path:_files' \\
			':path:_files' \\
${zshSpecsBlock(all, "text-json")}
		;;
	mcp)
		_arguments -C \\
			':directory:_files -/' \\
${zshSpecsBlock(all, "md-json")}
		;;
	*)
		_arguments -C \\
			':directory:_files -/' \\
${zshSpecsBlock(all, "md-json")}
		;;
	esac
}

_fln_init() {
	_arguments \\
${zshSpecsBlock(initOnly, "md-json")}
}

_fln_why() {
	_arguments \\
		':path:_files' \\
		':directory:_files -/' \\
${zshSpecsBlock(all, "text-json")}
}

_fln_doctor() {
	_arguments \\
		':directory:_files -/' \\
${zshSpecsBlock(all, "text-json")}
}

_fln "\${@}"
`;
}

function fishValueSuffix(
	spec: CliFlagSpec,
	formatKind: FormatCompletionKind,
): string {
	if (spec.type === "boolean") return "";
	if (spec.name === "format") return ` -xa "${formatValues(formatKind)}"`;

	return " -r";
}

function fishFlagLines(
	spec: CliFlagSpec,
	condition: string,
	formatKind: FormatCompletionKind,
): string[] {
	const lines: string[] = [];
	const suffix = fishValueSuffix(spec, formatKind);
	if (spec.short)
		lines.push(
			`complete -c fln ${condition} -s ${spec.short} -l ${spec.name}${suffix}`,
		);
	else lines.push(`complete -c fln ${condition} -l ${spec.name}${suffix}`);

	return lines;
}

function generateFish(): string {
	const all = flattenFlags();
	const initOnly = initFlags();
	const lines: string[] = [
		generatedBanner.trimEnd(),
		"# Fish completion for fln. Copy or symlink to ~/.config/fish/completions/fln.fish",
		"",
		"function __fln_needs_command",
		"\tset -l cmd (commandline -opc)",
		"\t[ (count $cmd) -eq 1 ]",
		"end",
		"",
		"function __fln_using_command -a name",
		"\tset -l cmd (commandline -opc)",
		"\t[ (count $cmd) -ge 2 ] && test $cmd[2] = $name",
		"end",
		"",
		"function __fln_not_subcommand",
		"\tset -l cmd (commandline -opc)",
		"\tif [ (count $cmd) -lt 2 ]",
		"\t\treturn 0",
		"\tend",
		`\tnot contains -- $cmd[2] ${CLI_SUBCOMMANDS.join(" ")}`,
		"end",
		"",
		"complete -c fln -f",
		'complete -c fln -n __fln_needs_command -a init -d "Generate fln.json config"',
		'complete -c fln -n __fln_needs_command -a why -d "Explain include/exclude for a path"',
		'complete -c fln -n __fln_needs_command -a doctor -d "Preflight scan without writing output"',
		'complete -c fln -n __fln_needs_command -a mcp -d "Start MCP server for AI agent integration"',
		'complete -c fln -n __fln_needs_command -a plan -d "Plan context within a token budget"',
		'complete -c fln -n __fln_needs_command -a diff -d "Diff two snapshots or a git ref"',
		'complete -c fln -n __fln_needs_command -a upgrade -d "Upgrade the fln binary"',
		"",
	];

	for (const spec of initOnly)
		lines.push(
			...fishFlagLines(spec, '-n "__fln_using_command init"', "md-json"),
		);

	for (const spec of all) {
		lines.push(
			...fishFlagLines(spec, '-n "__fln_using_command why"', "text-json"),
			...fishFlagLines(spec, '-n "__fln_using_command doctor"', "text-json"),
			...fishFlagLines(spec, '-n "__fln_using_command plan"', "md-json"),
			...fishFlagLines(spec, '-n "__fln_using_command diff"', "text-json"),
			...fishFlagLines(spec, "-n __fln_not_subcommand", "md-json"),
		);
	}

	lines.push(
		'complete -c fln -n "__fln_using_command why" -k -a "(__fish_complete_path)"',
		'complete -c fln -n "__fln_using_command doctor" -k -a "(__fish_complete_directories)"',
		'complete -c fln -n "__fln_using_command plan" -k -a "(__fish_complete_directories)"',
		'complete -c fln -n "__fln_using_command diff" -k -a "(__fish_complete_path)"',
		'complete -c fln -n __fln_not_subcommand -k -a "(__fish_complete_directories)"',
		"",
	);

	return `${lines.join("\n")}`;
}

function generatePowerShell(): string {
	const subcommands = CLI_SUBCOMMANDS.map((name) => `"${name}"`).join(", ");
	const globalFlags = flattenFlags()
		.flatMap((spec) => {
			const names = [`--${spec.name}`];
			if (spec.short) names.push(`-${spec.short}`);
			return names;
		})
		.map((name) => `"${name}"`)
		.join(", ");

	return `# Generated by scripts/generate-completions.ts — do not edit by hand.

Register-ArgumentCompleter -Native -CommandName fln -ScriptBlock {
	param($wordToComplete, $commandAst, $cursorPosition)
	$tokens = @($commandAst.ToString() -split '\\s+' | Where-Object { $_ })
	$command = if ($tokens.Count -gt 1) { $tokens[1] } else { '' }
	$subcommands = @(${subcommands})
	$flags = @(${globalFlags})

	if ($tokens.Count -le 1) {
		return $subcommands | Where-Object { $_ -like "$wordToComplete*" } | ForEach-Object {
			[System.Management.Automation.CompletionResult]::new($_, $_, 'ParameterValue', $_)
		}
	}

	if ($subcommands -contains $command) {
		return $flags | Where-Object { $_ -like "$wordToComplete*" } | ForEach-Object {
			[System.Management.Automation.CompletionResult]::new($_, $_, 'ParameterValue', $_)
		}
	}

	return $subcommands | Where-Object { $_ -like "$wordToComplete*" } | ForEach-Object {
		[System.Management.Automation.CompletionResult]::new($_, $_, 'ParameterValue', $_)
	}
}
`;
}

function writeCompletions(): void {
	mkdirSync(completionsDir, { recursive: true });
	writeFileSync(join(completionsDir, "fln.bash"), generateBash());
	writeFileSync(join(completionsDir, "_fln"), generateZsh());
	writeFileSync(join(completionsDir, "fln.fish"), generateFish());
	writeFileSync(join(completionsDir, "fln.ps1"), generatePowerShell());
	console.info(
		"✓ Wrote bash, zsh, fish, and PowerShell completions to completions/",
	);
}

writeCompletions();
