# Generated by scripts/generate-completions.ts — do not edit by hand.
# Fish completion for fln. Copy or symlink to ~/.config/fish/completions/fln.fish

function __fln_needs_command
	set -l cmd (commandline -opc)
	[ (count $cmd) -eq 1 ]
end

function __fln_using_command -a name
	set -l cmd (commandline -opc)
	[ (count $cmd) -ge 2 ] && test $cmd[2] = $name
end

function __fln_not_subcommand
	set -l cmd (commandline -opc)
	if [ (count $cmd) -lt 2 ]
		return 0
	end
	not contains -- $cmd[2] init why doctor mcp plan diff upgrade
end

complete -c fln -f
complete -c fln -n __fln_needs_command -a init -d "Generate fln.json config"
complete -c fln -n __fln_needs_command -a why -d "Explain include/exclude for a path"
complete -c fln -n __fln_needs_command -a doctor -d "Preflight scan without writing output"
complete -c fln -n __fln_needs_command -a mcp -d "Start MCP server for AI agent integration"
complete -c fln -n __fln_needs_command -a plan -d "Plan context within a token budget"
complete -c fln -n __fln_needs_command -a diff -d "Diff two snapshots or a git ref"
complete -c fln -n __fln_needs_command -a upgrade -d "Upgrade the fln binary"

complete -c fln -n "__fln_using_command init" -s w -l overwrite
complete -c fln -n "__fln_using_command init" -s v -l version
complete -c fln -n "__fln_using_command init" -s h -l help
complete -c fln -n "__fln_using_command why" -s o -l output -r
complete -c fln -n "__fln_using_command doctor" -s o -l output -r
complete -c fln -n "__fln_using_command plan" -s o -l output -r
complete -c fln -n "__fln_using_command diff" -s o -l output -r
complete -c fln -n __fln_not_subcommand -s o -l output -r
complete -c fln -n "__fln_using_command why" -s e -l exclude -r
complete -c fln -n "__fln_using_command doctor" -s e -l exclude -r
complete -c fln -n "__fln_using_command plan" -s e -l exclude -r
complete -c fln -n "__fln_using_command diff" -s e -l exclude -r
complete -c fln -n __fln_not_subcommand -s e -l exclude -r
complete -c fln -n "__fln_using_command why" -s i -l include -r
complete -c fln -n "__fln_using_command doctor" -s i -l include -r
complete -c fln -n "__fln_using_command plan" -s i -l include -r
complete -c fln -n "__fln_using_command diff" -s i -l include -r
complete -c fln -n __fln_not_subcommand -s i -l include -r
complete -c fln -n "__fln_using_command why" -l only -r
complete -c fln -n "__fln_using_command doctor" -l only -r
complete -c fln -n "__fln_using_command plan" -l only -r
complete -c fln -n "__fln_using_command diff" -l only -r
complete -c fln -n __fln_not_subcommand -l only -r
complete -c fln -n "__fln_using_command why" -l relevant -r
complete -c fln -n "__fln_using_command doctor" -l relevant -r
complete -c fln -n "__fln_using_command plan" -l relevant -r
complete -c fln -n "__fln_using_command diff" -l relevant -r
complete -c fln -n __fln_not_subcommand -l relevant -r
complete -c fln -n "__fln_using_command why" -l stdin
complete -c fln -n "__fln_using_command doctor" -l stdin
complete -c fln -n "__fln_using_command plan" -l stdin
complete -c fln -n "__fln_using_command diff" -l stdin
complete -c fln -n __fln_not_subcommand -l stdin
complete -c fln -n "__fln_using_command why" -l ext -r
complete -c fln -n "__fln_using_command doctor" -l ext -r
complete -c fln -n "__fln_using_command plan" -l ext -r
complete -c fln -n "__fln_using_command diff" -l ext -r
complete -c fln -n __fln_not_subcommand -l ext -r
complete -c fln -n "__fln_using_command why" -l include-hidden
complete -c fln -n "__fln_using_command doctor" -l include-hidden
complete -c fln -n "__fln_using_command plan" -l include-hidden
complete -c fln -n "__fln_using_command diff" -l include-hidden
complete -c fln -n __fln_not_subcommand -l include-hidden
complete -c fln -n "__fln_using_command why" -l no-gitignore
complete -c fln -n "__fln_using_command doctor" -l no-gitignore
complete -c fln -n "__fln_using_command plan" -l no-gitignore
complete -c fln -n "__fln_using_command diff" -l no-gitignore
complete -c fln -n __fln_not_subcommand -l no-gitignore
complete -c fln -n "__fln_using_command why" -l max-file-size -r
complete -c fln -n "__fln_using_command doctor" -l max-file-size -r
complete -c fln -n "__fln_using_command plan" -l max-file-size -r
complete -c fln -n "__fln_using_command diff" -l max-file-size -r
complete -c fln -n __fln_not_subcommand -l max-file-size -r
complete -c fln -n "__fln_using_command why" -l max-total-size -r
complete -c fln -n "__fln_using_command doctor" -l max-total-size -r
complete -c fln -n "__fln_using_command plan" -l max-total-size -r
complete -c fln -n "__fln_using_command diff" -l max-total-size -r
complete -c fln -n __fln_not_subcommand -l max-total-size -r
complete -c fln -n "__fln_using_command why" -l max-tokens -r
complete -c fln -n "__fln_using_command doctor" -l max-tokens -r
complete -c fln -n "__fln_using_command plan" -l max-tokens -r
complete -c fln -n "__fln_using_command diff" -l max-tokens -r
complete -c fln -n __fln_not_subcommand -l max-tokens -r
complete -c fln -n "__fln_using_command why" -l budget -r
complete -c fln -n "__fln_using_command doctor" -l budget -r
complete -c fln -n "__fln_using_command plan" -l budget -r
complete -c fln -n "__fln_using_command diff" -l budget -r
complete -c fln -n __fln_not_subcommand -l budget -r
complete -c fln -n "__fln_using_command why" -l max-content-tokens -r
complete -c fln -n "__fln_using_command doctor" -l max-content-tokens -r
complete -c fln -n "__fln_using_command plan" -l max-content-tokens -r
complete -c fln -n "__fln_using_command diff" -l max-content-tokens -r
complete -c fln -n __fln_not_subcommand -l max-content-tokens -r
complete -c fln -n "__fln_using_command why" -l token-model -r
complete -c fln -n "__fln_using_command doctor" -l token-model -r
complete -c fln -n "__fln_using_command plan" -l token-model -r
complete -c fln -n "__fln_using_command diff" -l token-model -r
complete -c fln -n __fln_not_subcommand -l token-model -r
complete -c fln -n "__fln_using_command why" -l security-check -r
complete -c fln -n "__fln_using_command doctor" -l security-check -r
complete -c fln -n "__fln_using_command plan" -l security-check -r
complete -c fln -n "__fln_using_command diff" -l security-check -r
complete -c fln -n __fln_not_subcommand -l security-check -r
complete -c fln -n "__fln_using_command why" -l recommend-budget -r
complete -c fln -n "__fln_using_command doctor" -l recommend-budget -r
complete -c fln -n "__fln_using_command plan" -l recommend-budget -r
complete -c fln -n "__fln_using_command diff" -l recommend-budget -r
complete -c fln -n __fln_not_subcommand -l recommend-budget -r
complete -c fln -n "__fln_using_command why" -l http
complete -c fln -n "__fln_using_command doctor" -l http
complete -c fln -n "__fln_using_command plan" -l http
complete -c fln -n "__fln_using_command diff" -l http
complete -c fln -n __fln_not_subcommand -l http
complete -c fln -n "__fln_using_command why" -l port -r
complete -c fln -n "__fln_using_command doctor" -l port -r
complete -c fln -n "__fln_using_command plan" -l port -r
complete -c fln -n "__fln_using_command diff" -l port -r
complete -c fln -n __fln_not_subcommand -l port -r
complete -c fln -n "__fln_using_command why" -l strict-limits
complete -c fln -n "__fln_using_command doctor" -l strict-limits
complete -c fln -n "__fln_using_command plan" -l strict-limits
complete -c fln -n "__fln_using_command diff" -l strict-limits
complete -c fln -n __fln_not_subcommand -l strict-limits
complete -c fln -n "__fln_using_command why" -l strict-toctou
complete -c fln -n "__fln_using_command doctor" -l strict-toctou
complete -c fln -n "__fln_using_command plan" -l strict-toctou
complete -c fln -n "__fln_using_command diff" -l strict-toctou
complete -c fln -n __fln_not_subcommand -l strict-toctou
complete -c fln -n "__fln_using_command why" -l annotate-tree -r
complete -c fln -n "__fln_using_command doctor" -l annotate-tree -r
complete -c fln -n "__fln_using_command plan" -l annotate-tree -r
complete -c fln -n "__fln_using_command diff" -l annotate-tree -r
complete -c fln -n __fln_not_subcommand -l annotate-tree -r
complete -c fln -n "__fln_using_command why" -l collect-todo
complete -c fln -n "__fln_using_command doctor" -l collect-todo
complete -c fln -n "__fln_using_command plan" -l collect-todo
complete -c fln -n "__fln_using_command diff" -l collect-todo
complete -c fln -n __fln_not_subcommand -l collect-todo
complete -c fln -n "__fln_using_command why" -l compress
complete -c fln -n "__fln_using_command doctor" -l compress
complete -c fln -n "__fln_using_command plan" -l compress
complete -c fln -n "__fln_using_command diff" -l compress
complete -c fln -n __fln_not_subcommand -l compress
complete -c fln -n "__fln_using_command why" -l outline
complete -c fln -n "__fln_using_command doctor" -l outline
complete -c fln -n "__fln_using_command plan" -l outline
complete -c fln -n "__fln_using_command diff" -l outline
complete -c fln -n __fln_not_subcommand -l outline
complete -c fln -n "__fln_using_command why" -l diff-hunks
complete -c fln -n "__fln_using_command doctor" -l diff-hunks
complete -c fln -n "__fln_using_command plan" -l diff-hunks
complete -c fln -n "__fln_using_command diff" -l diff-hunks
complete -c fln -n __fln_not_subcommand -l diff-hunks
complete -c fln -n "__fln_using_command why" -l encoding -r
complete -c fln -n "__fln_using_command doctor" -l encoding -r
complete -c fln -n "__fln_using_command plan" -l encoding -r
complete -c fln -n "__fln_using_command diff" -l encoding -r
complete -c fln -n __fln_not_subcommand -l encoding -r
complete -c fln -n "__fln_using_command why" -l output-split -r
complete -c fln -n "__fln_using_command doctor" -l output-split -r
complete -c fln -n "__fln_using_command plan" -l output-split -r
complete -c fln -n "__fln_using_command diff" -l output-split -r
complete -c fln -n __fln_not_subcommand -l output-split -r
complete -c fln -n "__fln_using_command why" -l no-contents
complete -c fln -n "__fln_using_command doctor" -l no-contents
complete -c fln -n "__fln_using_command plan" -l no-contents
complete -c fln -n "__fln_using_command diff" -l no-contents
complete -c fln -n __fln_not_subcommand -l no-contents
complete -c fln -n "__fln_using_command why" -l no-tree
complete -c fln -n "__fln_using_command doctor" -l no-tree
complete -c fln -n "__fln_using_command plan" -l no-tree
complete -c fln -n "__fln_using_command diff" -l no-tree
complete -c fln -n __fln_not_subcommand -l no-tree
complete -c fln -n "__fln_using_command why" -l format -xa "text json"
complete -c fln -n "__fln_using_command doctor" -l format -xa "text json"
complete -c fln -n "__fln_using_command plan" -l format -xa "md json"
complete -c fln -n "__fln_using_command diff" -l format -xa "text json"
complete -c fln -n __fln_not_subcommand -l format -xa "md json"
complete -c fln -n "__fln_using_command why" -l dry-run
complete -c fln -n "__fln_using_command doctor" -l dry-run
complete -c fln -n "__fln_using_command plan" -l dry-run
complete -c fln -n "__fln_using_command diff" -l dry-run
complete -c fln -n __fln_not_subcommand -l dry-run
complete -c fln -n "__fln_using_command why" -l stdout
complete -c fln -n "__fln_using_command doctor" -l stdout
complete -c fln -n "__fln_using_command plan" -l stdout
complete -c fln -n "__fln_using_command diff" -l stdout
complete -c fln -n __fln_not_subcommand -l stdout
complete -c fln -n "__fln_using_command why" -l copy
complete -c fln -n "__fln_using_command doctor" -l copy
complete -c fln -n "__fln_using_command plan" -l copy
complete -c fln -n "__fln_using_command diff" -l copy
complete -c fln -n __fln_not_subcommand -l copy
complete -c fln -n "__fln_using_command why" -s w -l overwrite
complete -c fln -n "__fln_using_command doctor" -s w -l overwrite
complete -c fln -n "__fln_using_command plan" -s w -l overwrite
complete -c fln -n "__fln_using_command diff" -s w -l overwrite
complete -c fln -n __fln_not_subcommand -s w -l overwrite
complete -c fln -n "__fln_using_command why" -s q -l quiet
complete -c fln -n "__fln_using_command doctor" -s q -l quiet
complete -c fln -n "__fln_using_command plan" -s q -l quiet
complete -c fln -n "__fln_using_command diff" -s q -l quiet
complete -c fln -n __fln_not_subcommand -s q -l quiet
complete -c fln -n "__fln_using_command why" -s V -l verbose
complete -c fln -n "__fln_using_command doctor" -s V -l verbose
complete -c fln -n "__fln_using_command plan" -s V -l verbose
complete -c fln -n "__fln_using_command diff" -s V -l verbose
complete -c fln -n __fln_not_subcommand -s V -l verbose
complete -c fln -n "__fln_using_command why" -l debug
complete -c fln -n "__fln_using_command doctor" -l debug
complete -c fln -n "__fln_using_command plan" -l debug
complete -c fln -n "__fln_using_command diff" -l debug
complete -c fln -n __fln_not_subcommand -l debug
complete -c fln -n "__fln_using_command why" -l no-ansi
complete -c fln -n "__fln_using_command doctor" -l no-ansi
complete -c fln -n "__fln_using_command plan" -l no-ansi
complete -c fln -n "__fln_using_command diff" -l no-ansi
complete -c fln -n __fln_not_subcommand -l no-ansi
complete -c fln -n "__fln_using_command why" -l follow-symlinks
complete -c fln -n "__fln_using_command doctor" -l follow-symlinks
complete -c fln -n "__fln_using_command plan" -l follow-symlinks
complete -c fln -n "__fln_using_command diff" -l follow-symlinks
complete -c fln -n __fln_not_subcommand -l follow-symlinks
complete -c fln -n "__fln_using_command why" -l no-sponsor-message
complete -c fln -n "__fln_using_command doctor" -l no-sponsor-message
complete -c fln -n "__fln_using_command plan" -l no-sponsor-message
complete -c fln -n "__fln_using_command diff" -l no-sponsor-message
complete -c fln -n __fln_not_subcommand -l no-sponsor-message
complete -c fln -n "__fln_using_command why" -l no-local-state
complete -c fln -n "__fln_using_command doctor" -l no-local-state
complete -c fln -n "__fln_using_command plan" -l no-local-state
complete -c fln -n "__fln_using_command diff" -l no-local-state
complete -c fln -n __fln_not_subcommand -l no-local-state
complete -c fln -n "__fln_using_command why" -l ignore-config
complete -c fln -n "__fln_using_command doctor" -l ignore-config
complete -c fln -n "__fln_using_command plan" -l ignore-config
complete -c fln -n "__fln_using_command diff" -l ignore-config
complete -c fln -n __fln_not_subcommand -l ignore-config
complete -c fln -n "__fln_using_command why" -l date -r
complete -c fln -n "__fln_using_command doctor" -l date -r
complete -c fln -n "__fln_using_command plan" -l date -r
complete -c fln -n "__fln_using_command diff" -l date -r
complete -c fln -n __fln_not_subcommand -l date -r
complete -c fln -n "__fln_using_command why" -l banner -r
complete -c fln -n "__fln_using_command doctor" -l banner -r
complete -c fln -n "__fln_using_command plan" -l banner -r
complete -c fln -n "__fln_using_command diff" -l banner -r
complete -c fln -n __fln_not_subcommand -l banner -r
complete -c fln -n "__fln_using_command why" -l banner-file -r
complete -c fln -n "__fln_using_command doctor" -l banner-file -r
complete -c fln -n "__fln_using_command plan" -l banner-file -r
complete -c fln -n "__fln_using_command diff" -l banner-file -r
complete -c fln -n __fln_not_subcommand -l banner-file -r
complete -c fln -n "__fln_using_command why" -l footer -r
complete -c fln -n "__fln_using_command doctor" -l footer -r
complete -c fln -n "__fln_using_command plan" -l footer -r
complete -c fln -n "__fln_using_command diff" -l footer -r
complete -c fln -n __fln_not_subcommand -l footer -r
complete -c fln -n "__fln_using_command why" -l footer-file -r
complete -c fln -n "__fln_using_command doctor" -l footer-file -r
complete -c fln -n "__fln_using_command plan" -l footer-file -r
complete -c fln -n "__fln_using_command diff" -l footer-file -r
complete -c fln -n __fln_not_subcommand -l footer-file -r
complete -c fln -n "__fln_using_command why" -l since -r
complete -c fln -n "__fln_using_command doctor" -l since -r
complete -c fln -n "__fln_using_command plan" -l since -r
complete -c fln -n "__fln_using_command diff" -l since -r
complete -c fln -n __fln_not_subcommand -l since -r
complete -c fln -n "__fln_using_command why" -s v -l version
complete -c fln -n "__fln_using_command doctor" -s v -l version
complete -c fln -n "__fln_using_command plan" -s v -l version
complete -c fln -n "__fln_using_command diff" -s v -l version
complete -c fln -n __fln_not_subcommand -s v -l version
complete -c fln -n "__fln_using_command why" -s h -l help
complete -c fln -n "__fln_using_command doctor" -s h -l help
complete -c fln -n "__fln_using_command plan" -s h -l help
complete -c fln -n "__fln_using_command diff" -s h -l help
complete -c fln -n __fln_not_subcommand -s h -l help
complete -c fln -n "__fln_using_command why" -k -a "(__fish_complete_path)"
complete -c fln -n "__fln_using_command doctor" -k -a "(__fish_complete_directories)"
complete -c fln -n "__fln_using_command plan" -k -a "(__fish_complete_directories)"
complete -c fln -n "__fln_using_command diff" -k -a "(__fish_complete_path)"
complete -c fln -n __fln_not_subcommand -k -a "(__fish_complete_directories)"
