# Generated by scripts/generate-completions.ts — do not edit by hand.

Register-ArgumentCompleter -Native -CommandName fln -ScriptBlock {
	param($wordToComplete, $commandAst, $cursorPosition)
	$tokens = @($commandAst.ToString() -split '\s+' | Where-Object { $_ })
	$command = if ($tokens.Count -gt 1) { $tokens[1] } else { '' }
	$subcommands = @("init", "why", "doctor", "mcp", "plan", "diff", "upgrade")
	$flags = @("--output", "-o", "--exclude", "-e", "--include", "-i", "--only", "--relevant", "--stdin", "--ext", "--include-hidden", "--no-gitignore", "--max-file-size", "--max-total-size", "--max-tokens", "--budget", "--max-content-tokens", "--token-model", "--security-check", "--recommend-budget", "--http", "--port", "--strict-limits", "--strict-toctou", "--annotate-tree", "--collect-todo", "--compress", "--outline", "--diff-hunks", "--encoding", "--output-split", "--no-contents", "--no-tree", "--format", "--dry-run", "--stdout", "--copy", "--overwrite", "-w", "--quiet", "-q", "--verbose", "-V", "--debug", "--no-ansi", "--follow-symlinks", "--no-sponsor-message", "--no-local-state", "--ignore-config", "--date", "--banner", "--banner-file", "--footer", "--footer-file", "--since", "--version", "-v", "--help", "-h")

	if ($tokens.Count -le 1) {
		return $subcommands | Where-Object { $_ -like "$wordToComplete*" } | ForEach-Object {
			[System.Management.Automation.CompletionResult]::new($_, $_, 'ParameterValue', $_)
		}
	}

	if ($subcommands -contains $command) {
		return $flags | Where-Object { $_ -like "$wordToComplete*" } | ForEach-Object {
			[System.Management.Automation.CompletionResult]::new($_, $_, 'ParameterValue', $_)
		}
	}

	return $subcommands | Where-Object { $_ -like "$wordToComplete*" } | ForEach-Object {
		[System.Management.Automation.CompletionResult]::new($_, $_, 'ParameterValue', $_)
	}
}
